### ISSUE TITLE
关于 links 的报错问题

### ISSUE THREAD

**Issue by StarsTesla** [leyiwang/nlp_research#3]
我运行时碰到了 links = map(lambda x: x.xpath(self.anthology_xpath_dict["links_node"])[0],
IndexError: list index out of range 的问题，可能因为有些paper没有link，所以我在lambda里加了个判断（links = map(lambda x: x.xpath(self.anthology_xpath_dict["links_node"])[0] if x.xpath(self.anthology_xpath_dict["links_node"]) else None,papers_nodes)
，希望及时更新下代码

**Comment by leyiwang** [comment]
谢谢，已经修复
